import express from "express";
import { api } from "../controller/Account/getAPI.mjs";
import { fetchBalances } from "../controller/Account/getBalance.mjs";
import { setindicator } from "../controller/Account/indicatorset.mjs";
import { signup } from "../controller/Account/signup.mjs";
import { signin } from "../controller/Account/signin.mjs";
import { signout } from "../controller/Account/signout.mjs";
import { getindicator } from "../controller/Account/getindicator.mjs";
import { getuser } from "../controller/Account/getuser.mjs";
const router = express.Router();

router.post("/setapi", api);
router.get("/getBalance", fetchBalances);
router.post("/setindicator", setindicator);
router.get("/getindicator", getindicator);
router.get("/getuser", getuser);
router.post("/signup", signup);
router.post("/signin", signin);
router.post("/signout", signout);
export default router;
